### GET ALL
GET http://localhost:3003/api/blogs

### GET BY ID
GET http://localhost:3003/api/blogs/66e84abba360bb70d58c0ee3

### POST
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "XVideos",
    "author": "XVIDEOS",
    "url": "https://XVIDEOS.COM/",
    "likes": 1000
}

### PUT
PUT http://localhost:3003/api/blogs/66e848e7a360bb70d58c0edf
Content-Type: application/json

{
    "likes": 100000000
}

### DELETE
DELETE http://localhost:3003/api/blogs/66e9abd51db472dbc1d74938