### GET ALL BLOGS
GET http://localhost:3003/api/blogs

### GET BY ID BLOG
GET http://localhost:3003/api/blogs/66e84abba360bb70d58c0ee3

### POST BLOG
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik51ZXZvVXN1YXJpbyIsImlkIjoiNjZmMWMwZjFmYzljMWE3MGJmOTJlNzBhIiwiaWF0IjoxNzI3MTgxMDg4LCJleHAiOjE3MjcxODQ2ODh9.s39gjekrDrOVfhAxe45HlWSgXaGTnbVxT6oH0bcaU_A

{
    "title": "CHECK",
    "author": "Nuevo Usuario",
    "url": "non url",
    "likes": 10,
    "user": "66f1c0f1fc9c1a70bf92e70a"
}

### PUT BLOG
PUT http://localhost:3003/api/blogs/66e848e7a360bb70d58c0edf
Content-Type: application/json

{
    "likes": 100000000
}

### DELETE BLOG only if you are the creator
DELETE http://localhost:3003/api/blogs/66f1c7bd5838cb5310fd1000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik51ZXZvVXN1YXJpbyIsImlkIjoiNjZmMWMwZjFmYzljMWE3MGJmOTJlNzBhIiwiaWF0IjoxNzI3MTgxMDg4LCJleHAiOjE3MjcxODQ2ODh9.s39gjekrDrOVfhAxe45HlWSgXaGTnbVxT6oH0bcaU_A

### GET ALL USERS
GET http://localhost:3003/api/users

### POST USER
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "NuevoUsuario",
    "name": "Nuevo Usuario",
    "password": "0000"
}

### POST LOGIN
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "NuevoUsuario",
    "password": "0000"
}