### GET /
GET http://localhost:3000/

### GET ALL
GET http://localhost:3000/api/persons

### GET BY ID
GET http://localhost:3000/api/persons/66e5a54048a8eb488e8b4216

### POST CREATE
POST http://localhost:3000/api/persons
Content-Type: application/json

{
    "name": "Sebastian Schneider",
    "number": "040-123456"
}

### DELETE
DELETE http://localhost:3000/api/persons/66e5a54048a8eb488e8b4216