### GET /
GET http://localhost:3000/

### GET ALL
GET http://localhost:3000/api/persons

### GET BY ID
GET http://localhost:3000/api/persons/66e5b672b9794f5d803b1594

### POST CREATE
POST http://localhost:3000/api/persons
Content-Type: application/json

{
    "name": "Martin Martinsen",
    "number": "115-788556"
}

### DELETE
DELETE http://localhost:3000/api/persons/66e5b451a7590fd3c749bfcf