# fly.toml app configuration file generated for part4-misty-dust-5951 on 2024-09-24T16:52:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part4-misty-dust-5951'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
