### GET ALL BLOGS
GET http://localhost:3003/api/blogs

### GET BY ID BLOG
GET http://localhost:3003/api/blogs/66e84abba360bb70d58c0ee3

### POST BLOG
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNjaG5laWRlclNlYmFzdGlhbiIsImlkIjoiNjZmMTZkZWU2NzQ4ZWQ5ZTYxMDlhOWRmIiwiaWF0IjoxNzI3MTg1MzAzLCJleHAiOjE3MjcxODg5MDN9.x3OxOAfFnegersTaMHGnEfBxwfZ2Ov7UyfoloQV4V3Y

{
    "title": "NUEVO POST",
    "author": "Sebastian Schneider",
    "url": "non url",
    "likes": 10,
    "user": "66f16dee6748ed9e6109a9df"
}

### PUT BLOG
PUT http://localhost:3003/api/blogs/66f17411637b77f177697496
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNjaG5laWRlclNlYmFzdGlhbiIsImlkIjoiNjZmMTZkZWU2NzQ4ZWQ5ZTYxMDlhOWRmIiwiaWF0IjoxNzI3MTg1MzAzLCJleHAiOjE3MjcxODg5MDN9.x3OxOAfFnegersTaMHGnEfBxwfZ2Ov7UyfoloQV4V3Y

{
    "likes": 800000000
}

### DELETE BLOG only if you are the creator
DELETE http://localhost:3003/api/blogs/66f2ca9f1eb735b12e09f313
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNjaG5laWRlclNlYmFzdGlhbiIsImlkIjoiNjZmMTZkZWU2NzQ4ZWQ5ZTYxMDlhOWRmIiwiaWF0IjoxNzI3MTg1MzAzLCJleHAiOjE3MjcxODg5MDN9.x3OxOAfFnegersTaMHGnEfBxwfZ2Ov7UyfoloQV4V3Y

### GET ALL USERS
GET http://localhost:3003/api/users

### POST USER
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "ZAjAZ",
    "name": "Zajaz",
    "password": "10101010"
}

### POST LOGIN
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "SchneiderSebastian",
    "password": "15673019"
}